server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: order
  feign:
    client:
      config:
        default:
          loggerLevel: full
          connect-timeout: 5000
          readTimeout: 10000

external-api:
  coupon: http://localhost:8082
  food: http://localhost:8083
  restaurant: http://localhost:8084
  users: http://localhost:8085
